import { Runeword } from './types';

export const RUNEWORDS: Runeword[] = [
  // Helms
  { id: 'h1', name: 'Nadir', category: 'Helm', itemTypes: ['Helm'], sockets: 2, runes: ['Nef', 'Tir'], minLevel: 13, stats: ['+50% Enhanced Defense', '+10 Defense', '+30 Defense vs. Missile', '+5 Strength', '+[4-6] to Mana after each Kill', '-33% Extra Gold from Monsters', '-3 to Light Radius', 'Level 13 Cloak of Shadows (9 Charges)'] },
  { id: 'h2', name: 'Radiance', category: 'Helm', itemTypes: ['Helm'], sockets: 3, runes: ['Nef', 'Sol', 'Ith'], minLevel: 27, stats: ['+[20-40]% Enhanced Damage', '+75% Enhanced Defense', '+30 Defense vs. Missile', '+10 to Vitality', '+10 to Energy', '+33 to Mana', 'Physical Damage Taken Reduced by 7', '15% Damage Taken Gained as Mana when Hit', '+5 to Light Radius'] },
  { id: 'h3', name: 'Lore', category: 'Helm', itemTypes: ['Helm'], sockets: 2, runes: ['Ort', 'Sol'], minLevel: 27, stats: ['+1 to All Skills', '+[5-10] to Energy', 'Lightning Resist +30%', 'Physical Damage Taken Reduced by 7', '+[1-2] to Mana after each Kill', '+2 to Light Radius'] },
  { id: 'h4', name: 'Wisdom', category: 'Helm', itemTypes: ['Helm'], sockets: 3, runes: ['Pul', 'Ith', 'Eld'], minLevel: 45, stats: ['+33% Chance to Pierce', '[15-25]% Bonus to Attack Rating', '[4-8]% Mana Stolen per Hit', '+50% Enhanced Defense', '+10 to Energy', '15% Slower Stamina Drain', 'Cannot Be Frozen', '+5 to Mana after each Kill', '15% Damage Gained as Mana when Hit'] },
  { id: 'h5', name: 'Delirium', category: 'Helm', itemTypes: ['Helm'], sockets: 3, runes: ['Lem', 'Ist', 'Io'], minLevel: 51, stats: ['11% Chance to Cast Level 18 Confuse on Striking', '6% Chance to Cast Level 14 Mind Blast when Struck', '14% Chance to Cast Level 13 Terror when Struck', '+2 to All Skills', '+261 Defense', '+10 to Vitality', '50% Extra Gold from Monsters', '30% Better Chance of Getting Magic Items', 'Level 17 Attract (60 Charges)'] },
  { id: 'h6', name: 'Flickering Flame', category: 'Helm', itemTypes: ['Helm'], sockets: 3, runes: ['Nef', 'Pul', 'Vex'], minLevel: 55, stats: ['Level [1-6] Resist Fire Aura when Equipped', '+2 to Fire Skills', '-[5-10]% to Enemy Fire Resistance', '+50% Enhanced Defense', '+30 Defense vs. Missile', '+[65-75] to Mana', '+4% to Maximum Fire Resist', 'Half Freeze Duration', 'Poison Length Reduced by 50%'] },
  { id: 'h7', name: 'Dream', category: 'Helm', itemTypes: ['Helm'], sockets: 3, runes: ['Io', 'Jah', 'Pul'], minLevel: 65, stats: ['10% Chance to Cast Level 15 Confuse when Struck', 'Level 14 Holy Shock Aura when Equipped', '+[20-30]% Faster Hit Recovery', '+50% Enhanced Defense', '+[150-220] Defense', '+10 to Vitality', 'Increase Maximum Life 5%', '+[0-61] to Mana (Based on Clvl)', 'All Resistances +[10-20]', '[20-30]% Better Chance of Getting Magic Items'] },
  { id: 'h8', name: 'Ferocity', category: 'Helm', itemTypes: ['Helm'], sockets: 3, runes: ['Zod', 'Cham', 'Shael'], minLevel: 69, stats: ['12% Chance to Cast Level 10 Taunt on Striking', 'Indestructible', '+20% Faster Hit Recovery', '[10-12]% Life Stolen per Hit', '+18 to Zeal', '+[150-200]% Enhanced Defense', 'Magic Damage Taken Reduced by [6-12]', 'Cannot Be Frozen', 'Attacker Takes Damage of [200-250]'] },

  // Chests
  { id: 'c1', name: 'Stealth', category: 'Chest', itemTypes: ['Chest'], sockets: 2, runes: ['Tal', 'Eth'], minLevel: 17, stats: ['+10% Faster Run/Walk', '+20% Faster Cast Rate', '+20% Faster Hit Recovery', '+6 to Dexterity', 'Regenerate Mana 15%', '+15 Maximum Stamina', 'Poison Resist +30%', 'Magic Damage Taken Reduced by 3'] },
  { id: 'c2', name: 'Peace', category: 'Chest', itemTypes: ['Chest'], sockets: 3, runes: ['Shael', 'Thul', 'Amn'], minLevel: 29, stats: ['You May Summon 1 Additional Valkyrie', '8% Chance to Cast Level 12 Slow Movement when Struck', '+1 to Amazon Skills', '+20% Faster Hit Recovery', '+2 to Critical Strike', 'Cold Resist +30%', 'Attacker Takes Damage of 20'] },
  { id: 'c3', name: 'Myth', category: 'Chest', itemTypes: ['Chest'], sockets: 3, runes: ['Hel', 'Amn', 'Nef'], minLevel: 25, stats: ['5% Chance to Cast Level 1 Taunt on Striking', '3% Chance to Cast Level 1 Howl when Struck', '+[1-2] to Barbarian Skills', '+30 Defense vs. Missile', 'Replenish Life +10', '+[3-4] to Mana after each Kill', 'Attacker Takes Damage of 20', 'Attacker Takes Damage of [2-297] (Based on Clvl)', 'Requirements -15%'] },
  { id: 'c4', name: 'Smoke', category: 'Chest', itemTypes: ['Chest'], sockets: 2, runes: ['Nef', 'Lum'], minLevel: 37, stats: ['+20% Faster Hit Recovery', '+75% Enhanced Defense', '+280 Defense vs. Missile', '+10 to Energy', 'All Resistances +[30-50]', '-1 to Light Radius', 'Level 6 Weaken (18 Charges)'] },
  { id: 'c5', name: 'Hustle', category: 'Chest', itemTypes: ['Chest'], sockets: 3, runes: ['Shael', 'Ko', 'Eld'], minLevel: 39, stats: ['Level 6 Burst of Speed When Equipped', '+20% Increased Attack Speed', '+20% Faster Hit Recovery', '+10 to Dexterity', '50% Slower Stamina Drain', 'All Resistances +10', 'Half Freeze Duration'] },
  { id: 'c6', name: 'Lionheart', category: 'Chest', itemTypes: ['Chest'], sockets: 3, runes: ['Hel', 'Lum', 'Fal'], minLevel: 41, stats: ['+[80-110]% Enhanced Damage', '+[10-25] to Strength', '+[10-15] to Dexterity', '+[10-20] to Vitality', '+10 to Energy', '+50 to Life', 'All Resistances +[20-30]', 'Requirements -15%'] },
  { id: 'c7', name: 'Treachery', category: 'Chest', itemTypes: ['Chest'], sockets: 3, runes: ['Shael', 'Thul', 'Lem'], minLevel: 43, stats: ['25% Chance to Cast Level 15 Venom on Striking', '15% Chance to Cast Level 21 Mind Blast when Struck', '+2 to Assassin Skills', '+45% Increased Attack Speed', '+20% Faster Hit Recovery', 'Cold Resist +30%', '50% Extra Gold from Monsters'] },
  { id: 'c8', name: 'Enigma', category: 'Chest', itemTypes: ['Chest'], sockets: 3, runes: ['Jah', 'Ith', 'Ber'], minLevel: 65, stats: ['+2 to All Skills', '+25% Faster Run/Walk', 'Level 1 Blink (5 Charges)', '+[500-775] Defense', '+[0-74] to Strength (Based on Clvl)', 'Increase Maximum Life 5%', 'Physical Damage Taken Reduced by 6%', '15% Damage Taken Gained as Mana when Hit', '[0-74]% Better Chance of Getting Magic Items (Based on Clvl)'] },
  { id: 'c9', name: 'Innocence', category: 'Chest', itemTypes: ['Chest'], sockets: 4, runes: ['Gul', 'Lem', 'Zod', 'Hel'], minLevel: 69, stats: ['Indestructible', 'Level [8-12] Blade Shield When Equipped', '+2 to All Skills', '+20% Chance of Crushing Blow', '+[200-275]% Enhanced Defense', '+4% to Maximum Poison Resist', 'Poison Length Reduced by 50%', 'Attacker Takes Damage of [600-800]', '50% Extra Gold from Monsters', 'Requirements -25%'] },
  { id: 'c10', name: 'Fortitude', category: 'Chest', itemTypes: ['Chest'], sockets: 4, runes: ['El', 'Sol', 'Dol', 'Lo'], minLevel: 59, stats: ['+25% Faster Cast Rate', '+[250-300]% Enhanced Damage', '+200% Enhanced Defense', '+15 Defense', '+[1-148] to Life (Based on Clvl)', 'Replenish Life +20', '+4% to Maximum Lightning Resist', 'All Resistances +[25-30]', 'Physical Damage Taken Reduced by 7', '12% Damage Taken Gained as Mana when Hit', '+1 to Light Radius'] },

  // Shields
  { id: 's1', name: 'Spirit', category: 'Shield', itemTypes: ['Shield'], sockets: 4, runes: ['Tal', 'Thul', 'Ort', 'Amn'], minLevel: 25, stats: ['+1 to All Skills', '+[25-35]% Faster Cast Rate', '+25% Faster Hit Recovery', '+[11-22] to Vitality', '+[59-82] to Mana', 'Cold Resist +35%', 'Lightning Resist +35%', 'Poison Resist +35%', '+[3-8] Magic Absorb', 'Attacker Takes Damage of 24', 'Requirements -15%'] },
  { id: 's2', name: 'Ancients\' Pledge', category: 'Shield', itemTypes: ['Shield'], sockets: 3, runes: ['Ral', 'Ort', 'Tal'], minLevel: 21, stats: ['+50% Enhanced Defense', 'Cold Resist +43%', 'Lightning Resist +48%', 'Fire Resist +48%', 'Poison Resist +48%', '10% Damage Taken Gained as Mana when Hit'] },
  { id: 's3', name: 'Rhyme', category: 'Shield', itemTypes: ['Shield'], sockets: 2, runes: ['Shael', 'Eth'], minLevel: 29, stats: ['+40% Faster Block Rate', '20% Increased Chance of Blocking', 'Regenerate Mana 15%', 'All Resistances +25', 'Cannot Be Frozen', '50% Extra Gold from Monsters', '25% Better Chance of Getting Magic Items'] },
  { id: 's4', name: 'Exile', category: 'Shield', itemTypes: ['Paladin Shield', 'Shield'], sockets: 4, runes: ['Vex', 'Ohm', 'Ist', 'Dol'], minLevel: 57, stats: ['25% Chance to Cast level 18 Decrepify on Striking', 'Level [13-16] Defiance Aura when Equipped', '+2 to Offensive Auras (Paladin Only)', '+30% Faster Block Rate', 'Freezes Target', '+[220-260]% Enhanced Defense', 'Replenish Life +30', '+4% to Maximum Cold Resist', '+4% to Maximum Fire Resist', '30% Better Chance of Getting Magic Items', 'Repairs 1 Durability Every 4 Seconds'] },
  { id: 's5', name: 'Phoenix', category: 'Shield', itemTypes: ['Shield'], sockets: 4, runes: ['Vex', 'Vex', 'Lo', 'Jah'], minLevel: 65, stats: ['20% Chance to Cast Level 40 Firestorm on Striking', '100% Chance to Cast Level 40 Blaze when you Level-Up', 'Level [10-12] Redemption Aura when Equipped', '+[250-300]% Enhanced Damage', '-28% to Enemy Fire Resistance', '+[350-400] Defense vs. Missile', '+75 to Life', '+4% to Maximum Lightning Resist', '+8% to Maximum Fire Resist'] },
  
  // Quivers
  { id: 'q1', name: 'Ancient\'s Scripture', category: 'Quiver', itemTypes: ['Quiver'], sockets: 2, runes: ['Tal', 'Ort'], minLevel: 21, stats: ['+[10-20]% Enhanced Damage', '+20 to Life', 'Heal Stamina Plus 20%', 'Lightning Resist +[40-50]%', 'Poison Resist +[40-50]%'] },
  { id: 'q2', name: 'Echo', category: 'Quiver', itemTypes: ['Quiver'], sockets: 2, runes: ['Sol', 'Dol'], minLevel: 31, stats: ['+[20-30]% Chance to Pierce', '+[20-30]% Enhanced Damage', '50% Bonus to Attack Rating', 'Replenish Life +30', 'Physical Damage Taken Reduced By 9', '+2 Life after each Kill'] },

  // Weapons
  { id: 'w1', name: 'Steel', category: 'Weapon', itemTypes: ['Sword', 'Axe', 'Mace', 'Claw', 'Throwing Weapon'], sockets: 2, runes: ['Tir', 'El'], minLevel: 13, stats: ['+25% Increased Attack Speed', '+20% Enhanced Damage', '+3 to Minimum Damage', '+3 to Maximum Damage', '+50 to Attack Rating', '+50% Chance of Open Wounds', '+2 to Mana after each Kill', '+1 to Light Radius'] },
  { id: 'w2', name: 'Malice', category: 'Weapon', itemTypes: ['Melee Weapon', 'Throwing Weapon'], sockets: 3, runes: ['Ith', 'El', 'Eth'], minLevel: 15, stats: ['+33% Enhanced Damage', '+9 to Maximum Damage', '-25% Target Defense', '+50 to Attack Rating', '+100% Chance of Open Wounds', '+6 Open Wounds Damage per Second', 'Prevent Monster Heal', '-100 to Monster Defense per Hit', 'Drain Life -5'] },
  { id: 'w3', name: 'Leaf', category: 'Weapon', itemTypes: ['Staff'], sockets: 2, runes: ['Tir', 'Ral'], minLevel: 19, stats: ['+3 to Fire Skills', 'Adds 5-30 Fire Damage', '+[1-2] to Inferno (Sorceress Only)', '+3 to Warmth (Sorceress Only)', '+3 to Fire Bolt (Sorceress Only)', '+[2-198] Defense (Based on Clvl)', 'Cold Resist +33%', '+2 to Mana after each Kill'] },
  { id: 'w4', name: 'Spirit', category: 'Weapon', itemTypes: ['Sword', 'Staff'], sockets: 4, runes: ['Tal', 'Thul', 'Ort', 'Amn'], minLevel: 25, stats: ['+1 to All Skills (Non-Staves)', '+2 to All Skills (Staves)', '+[25-35]% Faster Cast Rate', '+25% Faster Hit Recovery (Non-Staves)', '+55% Faster Hit Recovery (Staves)', 'Adds 1-50 Lightning Damage', 'Adds 3-14 Cold Damage', '+75 Poison Damage over 5 Seconds', '7% Life Stolen per Hit', '+[11-22] to Vitality', '+[59-82] to Mana', '+[3-8] Magic Absorb', 'Requirements -15%'] },
  { id: 'w5', name: 'Insight', category: 'Weapon', itemTypes: ['Staff', 'Polearm', 'Spear'], sockets: 4, runes: ['Ral', 'Tir', 'Tal', 'Sol'], minLevel: 27, stats: ['Level [12-17] Meditation Aura when Equipped', '+35% Faster Cast Rate', '+[180-240]% Enhanced Damage', '+9 to Minimum Damage', '[180-250]% Bonus to Attack Rating', 'Adds 5-30 Fire Damage', '+75 Poison Damage over 5 Seconds', '+[1-6] to Critical Strike', '+[10-20] to All Attributes', '+2 to Mana after each Kill', '23% Better Chance of Getting Magic Items'] },
  { id: 'w6', name: 'Heart of the Oak', category: 'Weapon', itemTypes: ['Staff', 'Mace'], sockets: 4, runes: ['Ko', 'Vex', 'Pul', 'Thul'], minLevel: 55, stats: ['+3 to All Skills', '+30% Faster Cast Rate', '+75% Damage to Demons', '+100 to Attack Rating against Demons', 'Adds 3-14 Cold Damage', '7% Mana Stolen per Hit', '+10 to Dexterity', 'Replenish Life +20', 'Increase Maximum Mana 15%', 'All Resistances +[20-30]', 'Level 4 Oak Sage (25 Charges)', 'Level 14 Raven (60 Charges)'] },
  { id: 'w7', name: 'Grief', category: 'Weapon', itemTypes: ['Sword', 'Axe', 'Polearm'], sockets: 5, runes: ['Eth', 'Tir', 'Lo', 'Mal', 'Ral'], minLevel: 59, stats: ['35% Chance to Cast Level 15 Venom on Striking', '+[30-40]% Increased Attack Speed', 'Adds 280 to [320-360] Damage', '-25% Target Defense', '+[1-185]% Damage to Demons (Based on Clvl)', 'Adds 5-30 Fire Damage', '-[15-20]% to Enemy Poison Resistance', '+20% Deadly Strike', 'Prevent Monster Heal', '+2 to Mana after each Kill', '+[10-15] Life after each Kill'] },
  { id: 'w8', name: 'Breath of the Dying', category: 'Weapon', itemTypes: ['Weapon'], sockets: 6, runes: ['Vex', 'Hel', 'El', 'Eld', 'Zod', 'Eth'], minLevel: 69, stats: ['35% Chance to Cast Level 40 Poison Nova on Striking', 'Indestructible', '+60% Increased Attack Speed', '+[350-400]% Enhanced Damage', '-25% Target Defense', '+50 to Attack Rating', '+200% Damage to Undead', '+50 to Attack Rating against Undead', '7% Mana Stolen per Hit', '[8-12]% Life Stolen per Hit', 'Prevent Monster Heal', '+30 to All Attributes', '+1 to Light Radius', 'Requirements -20%'] },
  { id: 'w9', name: 'Infinity', category: 'Weapon', itemTypes: ['Polearm', 'Spear', 'Staff'], sockets: 4, runes: ['Ber', 'Mal', 'Ber', 'Ist'], minLevel: 63, stats: ['25% Chance to Cast Level 20 Chain Lightning on Striking (Non-Staves)', '15% Chance to Cast Level 20 Chain Lightning on Casting (Staves)', 'Level 12 Conviction Aura when Equipped', '+35% Faster Run/Walk', '+35% Faster Cast Rate (Staves Only)', '+[255-325]% Enhanced Damage', '-[45-55]% to Enemy Lightning Resistance', '+40% Chance of Crushing Blow', 'Prevent Monster Heal', '+[0-49] to Vitality (Based on Clvl)', '30% Better Chance of Getting Magic Items'] },
  { id: 'w10', name: 'Call to Arms', category: 'Weapon', itemTypes: ['Weapon'], sockets: 5, runes: ['Amn', 'Ral', 'Mal', 'Ist', 'Ohm'], minLevel: 57, stats: ['+1 to All Skills', '+40% Increased Attack Speed', '+[245-285]% Enhanced Damage', 'Adds 5-30 Fire Damage', '7% Life Stolen per Hit', 'Prevent Monster Heal', '+[2-6] to Battle Command', '+[2-6] to Battle Orders', '+[1-3] to Battle Cry', 'Replenish Life +12', '30% Better Chance of Getting Magic Items'] },
];

// Helper to get all unique runes
export const ALL_RUNES = Array.from(new Set(RUNEWORDS.flatMap(r => r.runes))).sort();

// Helper to get all unique item types
export const ALL_ITEM_TYPES = Array.from(new Set(RUNEWORDS.flatMap(r => r.itemTypes))).sort();
